# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: agente-premia
  vmImage: ubuntu-latest

stages:
- stage: Test_Build1
  # condition: false
  jobs:
  - job: Test_Automation
    # continueOnError: true
    steps:
        - checkout: self
        - script: which mvn
        - script: pwd; ls -ltr
        - task: Cache@2
          inputs:
                key: 'maven | "$(Agent.OS)" | pom.xml'
                restoreKeys: |
                      maven | "$(Agent.OS)"
                      maven
                path: $(MAVEN_CACHE_FOLDER)
          displayName: Cache Maven local repo
        - script: |
                    env | sort
                    echo "$(Build.SourceVersionMessage)"
        - script: /usr/bin/mvn -f pom.xml clean test
          condition: not(startsWith(variables['Build.SourceVersionMessage'], 'noBuild'))
          displayName: Build Artifact